spring:
  application:
    name: cloud-config-server
  cloud:
    services:
      registrationMethod: route

    #cloud config
    config:
      server:
        git:
          uri: https://github.com/JunTestGit/cloudConfig.git
          username: JunTestGit
          password: juntestgit1994


server:
  port: 9093

producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  isSecure: false
security:
  basic:
    enabled: false
