#spring:
#    application:
#        name: assignforce-trainer-service
#    #DATABASE CONFIG ISSUE: CANNOT USE ENVIRONMENT VARIABLE
#    datasource:
##        url: jdbc:oracle:thin:@assignforce.chueiwozbnfz.us-east-1.rds.amazonaws.com:1521:ORCL
##        username:
##        password:
#        url: jdbc:oracle:thin:@assignforce.chueiwozbnfz.us-east-1.rds.amazonaws.com:1521:ORCL
#        username: assignforce_dev
#        password: pVCwxTn3
#    #HIBERNATE
#    jpa:
#        database-platform: org.hibernate.dialect.Oracle10gDialect
#
server:
  port: 9093

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    lease: 5
#    healthcheck:
#      enabled: false
#  instance:
#    lease-expiration-duration-in-seconds: 2
#    lease-renewal-interval-in-seconds: 1
spring:
  application:
    name: trainerService
  cloud:
    services:
      registrationMethod: route
  data:
    mongodb:
      uri: mongodb://location:locationpw@ds163656.mlab.com:63656/assignforce-location-dev

producer:          //I don't know what this does but it was in pivotals sample application
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  isSecure: false  //temporary allows open access to endpoint



